### ISSUE TITLE
Double underscores are replaced with simple

### ISSUE THREAD

**Issue by sregg** [mpyw/axios-case-converter#11]
When I use 

```
axios.get('/bla', {
    params: {
        foo__bar: 1234
    }
  })
```

the generated url is `/bla?foo_bar` instead of `/bla?foo__bar`

**Comment by mpyw** [comment]
Thanks for reporting, but this is an issue of `change-case` package.
You can choose one of the following options:

- Change server app implementation if you can manage it
- Fork `axios-case-converter` and overwrite case-conversion functions by yourself
- Fork `axios-case-converter` and implement flexible options to submit an pull request

**Comment by Myzel394** [comment]
Quick tip for anyone who comes across this in the future:
Just create your own interceptor using [`camelcase-keys`](https://github.com/sindresorhus/camelcase-keys) and [`snakecase-keys`](https://github.com/bendrucker/snakecase-keys).

Here is a little snippet I made:

```
// Camelcase response
instance.interceptors.response.use(response =>
    camelcaseKeys(response, {deep: true}));

// Snakecase request
instance.interceptors.request.use(response =>
    snakecaseKeys(response));
```

**Comment by mpyw** [comment]
This issue can be resolved on the latest version. We can customize the case functions.

**Comment by Myzel394** [comment]
Ok finally found out my method above DOES NOT WORK! I was snakecasing the whole request (axios config also got snakecased), but only required to snakecase `params` and `data`.

Here is the updated version (this version also only camelcases the `response.data`):

  
```
// Camelcase response
instance.interceptors.response.use(response => {
    camelcaseKeys(response.data ?? {}, {deep: true});

    return response;
});

// Snakecase request
instance.interceptors.request.use(config => {
    snakecaseKeys(config.data ?? {}, {deep: true});
    snakecaseKeys(config.params ?? {}, {deep: true});

    return config;
});
```

**Comment by mpyw** [comment]
https://github.com/mpyw/axios-case-converter#casefunctions--snake-function-camel-function-header-function-
