### ISSUE TITLE
Add option to preserve uuids

### ISSUE THREAD

**Issue by manuelbieh** [mpyw/axios-case-converter#12]
I was recently hunting down a bug in an application where object keys appeared to be missing (although I could see them in the API response) only to later find out that they were (of course) converted to "camelcase". So
`445ebf68-bd0e-44c6-b6b8-a70d9ba08115` became `445ebf68Bd0e44c6B6b8A70d9ba08115`.

Would be nice to have an option like `{ preserveUuid: true }` to not convert UUIDs (or possibly other formats) to camelCase. If you're interested, I could build that and create a PR.

Another, more flexible option would be something like a `preservePattern: RegExp` so a user could specify which keys should not be converted but I think `preserveUuid` would be fine for the beginning 😉

Ping me if you're interested!

**Comment by cjancsar** [comment]
Why would the value of a response be converted to camel case? Shouldn't just the keys be converted?
