### ISSUE TITLE
Exempt certain fields/nested fields from case conversion

### ISSUE THREAD

**Issue by sirajulm** [mpyw/axios-case-converter#17]
It would be nice to have an options that help you to exempt certain fields from being converted.

For example, we have a field `_destroy` received from the backend, but after camelCasing it converts to `destroy`. There is no possibility to send back the field to the API's as `_destroy`,since _.snakeCase(`_destroy`) or _.snakeCase(`destroy`) returns the value as `destroy`

It will be good if we can have something likethis: 
```javascript 
// applyConverters(<axiosInstance>, [<converterOptions>] )
applyConverters(axios.create(), { exception: ['_destroy'] } )
```

**Comment by smithmr** [comment]
Need an override for case converting for sure, we have query params on our backend for filter lists that require double underscores `{amount__lte: "5000"}` for example

**Comment by mpyw** [comment]
Sorry, actually it needs fully customizable interface on this library

**Comment by sirajulm** [comment]
@mpyw I'll find some time looking into the issue and adding an option to exclude user specified keys.
