### ISSUE TITLE
How to disable headers processing?

### ISSUE THREAD

**Issue by losikov** [mpyw/axios-case-converter#20]
The library is perfect.
I would prefer to see headers untouched. Is there any options to disable HTTP headers processing completely, disable it once, and don't worry about keeping **preservedKeys** up to date.
Thanks.

**Comment by mpyw** [comment]
Is this work?

```ts
import { camel, header, snake } from "axios-case-converter/lib/transform";

const options = {
  preservedKeys: [], // Omittable
  converters: {
    snakeRequest: (data) => snake(data, options),
    camelResponse: (data) => camel(data, options),
  },
}

const client = applyConverters(axios.create(), options);
```

But it looks dirty, it should be implemented as a core feature.

**Comment by mpyw** [comment]
With #22, you can do like this:

```js
const client = applyConverters(axios.create(), { ignoreHeaders: true });
```
