### ISSUE TITLE
preservedKeys nested wildcards

### ISSUE THREAD

**Issue by glenncoppens** [mpyw/axios-case-converter#28]
Hi, 

Nice work you did! 
So there's two options to preserve key names, `string[]` and `Function`.
I'm currently using the string[] approach, but it might be useful to only apply the middleware only on a subset of the request/response data. 

Eg in a Json api there's (very often) extra metadata included in the response:
```js
const requestData = {
  data : {
    data: {
      name: 'name',
      billing_street: 'street name',
      ...
    },
    meta: {
      current_page: 1,
      from: 1, 
      ...
    },
    ...
  }
}
```

Can we use the Functions-approach here so that the casing middleware is only applied on the `data.data` attribute?

Thanks!

**Comment by mpyw** [comment]
Nice idea! But it looks a little hard to implement 🤔

**Comment by glenncoppens** [comment]
I didn't really check your current underlying approach to rename the keys.

But what if the object is flattened and thén the keys are being renamed (and then unflatten again)? Then you could include `'data.data'` or exclude `'data.meta'`..
But I'm afraid the problem here may be performance degradation 🤔
Not sure what performance impact of eg https://github.com/hughsk/flat is..

**Comment by mpyw** [comment]
Yes, flattening all elements will have a large performance degression.

**Comment by mpyw** [comment]
Yes, flattening all elements will have a large performance degradation. And we'll get into trouble on reshaping objects because this library accepts not only plain objects but also `FormData` `URLSearchParams`...

**Comment by mpyw** [comment]
Extend `CaseFunction` to accept 3rd argument like `context`? But it may have a medium or large impact...

![image](https://user-images.githubusercontent.com/1351893/81468511-fd052800-921a-11ea-92e8-48fa5b743729.png)
