### ISSUE TITLE
Not working with JSON.stringify on FormData

### ISSUE THREAD

**Issue by ngekoding** [mpyw/axios-case-converter#29]
Hi, nice to found this awesome library.
I try to use this in my project, but I got the library not covert camelCase to snake_case when sending data with JSON.stringify on FormData.

**OS:** macOS Mojave
**Browser:** Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

And here my code:

// helper: api.js 
```
const API = applyCaseMiddleware(
  Axios.create({
    baseURL: 'http://mysite.com/api/v1/',
    headers: {
      'X-Requested-With': 'xmlhttprequest'
    },
  })
);

export default API;
```

// main.js
```
const formData = new FormData();
formData.append('document', null);
formData.append('keterangan', this.form.keterangan);
formData.append('approvers', JSON.stringify(approvers));
API.post('/api/v1/document/store', formData, {
	headers: { 'Content-Type': 'multipart/form-data' }
}).then(res => {
// success
}).catch(err => {
// something went wrong
});
```

And when checking the browser console, I got this:
<img width="666" alt="Not converted" src="https://user-images.githubusercontent.com/11625690/87894277-85e6de00-ca6c-11ea-9b67-0fc8dbe10c1b.png">

The data attributes still in camelCase.

How can I fix this?

**Comment by ahmedosama5200** [comment]
Are you planning to fix that ?

**Comment by ytoune** [comment]
```js
const formdata = new FormData()
// this should be treated as plain text
formdata.append('foo', JSON.stringify({ foo: 12 }))
// this should be treated as json
formdata.append('bar', new Blob([JSON.stringify({ foo: 12 })], {
  type: 'application/json',
}), 'bar.json')
// ?
formdata.append('baz', new Blob(['<example/>'], {
  type: 'application/xml',
}), 'baz.xml')
```

**Comment by mpyw** [comment]
After rethink, I realized this is the expected behavior. *Stringified JSON* is just `string`, not JSON.
