### ISSUE TITLE
Incorrect peer dependency

### ISSUE THREAD

**Issue by aabanaag** [mpyw/axios-case-converter#32]
Axios is currently as 0.20, should this package also update the version to 0.20?

**Comment by mpyw** [comment]
Any PRs are welcome!

**Comment by aabanaag** [comment]
#33

**Comment by mpyw** [comment]
In favor of [Update axios dependency to 0.21.1 by davidfishlock · Pull Request #34 · mpyw/axios-case-converter](https://github.com/mpyw/axios-case-converter/pull/34)
