### ISSUE TITLE
Axios v1.0.0 compatibility

### ISSUE THREAD

**Issue by tobidalhof** [mpyw/axios-case-converter#45]
Axios v1.0.0 got released a few days ago (see https://github.com/axios/axios/releases/tag/v1.0.0) but `axios-case-converter` only works with versions between >=0.23.0 and <1.0.0 unfortunately.

![image](https://user-images.githubusercontent.com/10046578/194709478-846f6644-5135-4fbf-9db0-6cbeaa4e03fb.png)

Thank you for creating this package, I found it very useful.

**Comment by mpyw** [comment]
Sorry, I'll catch up those changes! Thanks for reporting

**Comment by mpyw** [comment]
My colleague @siketyan will help our project 🔥
