### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by sergeu90** [mpyw/axios-case-converter#51]
Hi. After updated to latest version i have problem 

![image](https://user-images.githubusercontent.com/7217517/195889399-33d38230-4ba0-46d8-8e56-4629d24b1060.png)

I think need to check on  'undefined' 

![image](https://user-images.githubusercontent.com/7217517/195889763-adbf0ed4-3942-4ca8-8d91-154d228697d6.png)

**Comment by mpyw** [comment]
Oops! Nice catch
