### ISSUE TITLE
Response headers aren't being converted for axios 1.x

### ISSUE THREAD

**Issue by joaolrpm** [mpyw/axios-case-converter#59]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

I wanted to bring to your attention an issue I encountered while working on a project that involves updating `axios` from version `0.24.0` to `1.x` and `axios-case-converter` from version `0.9.0` to `1.1.0`.

After the update, I observed a problem related to response headers case conversion. After some debugging, I narrowed down the issue to the `overwriteHeadersOrNoop` function, particularly the validation within it:

```ts
if (
    options?.ignoreHeaders ||
    (!isPlainObject(headers) && !isAxiosHeaders(headers))
)
```

Upon investigation, it seems that the problem arises when the project is deployed, involving bundling, minification, and obfuscation. The `isAxiosHeaders(headers)` validation fails, even though the headers are, in fact, of type `AxiosHeaders`. This occurs because the validation relies on checking the constructor name.

Is there a reason for the use of the constructor name instead of validating whether it is an instance of `AxiosHeaders`?

To confirm this behavior, I made a patch to the `axios-case-converter@1.1.0` and added some log statements to the code:

```ts
import { AxiosHeaders } from "axios";

...

const overwriteHeadersOrNoop = (
    ...
): void => {
    console.log(
        `isPlainObject: ${isPlainObject(headers)},
         isAxiosHeaders: ${isAxiosHeaders(headers)},
         instanceof: ${headers instanceof AxiosHeaders}
    `);
}
```

When running the code locally, the logs showed the expected results. However, after deployment, the logs indicated that `isAxiosHeaders(headers)` was returning `false`, even though `headers instanceof AxiosHeaders` was `true`.

Local Logs:
![local](https://github.com/mpyw/axios-case-converter/assets/92136951/16f823da-49d7-4aa8-8f51-38a22859eeac)

Deployed Logs:
![docker-compose](https://github.com/mpyw/axios-case-converter/assets/92136951/63cfea2a-a81f-4015-bd42-b8a168a7a6d2)

It appears that the issue might be related to the obfuscation process affecting the constructor name comparison.

For additional context, here is the configuration for the Axios instance and the relevant request:

**Axios Instance:**

```ts
const axiosInstance = applyConverters(
  axios.create({
    baseURL: SOME_URL,
    timeout: 10000,
    paramsSerializer: (params) => stringify(params, { arrayFormat: 'repeat' }),
  })
);
```

**Request:**

```ts
axiosInstance.post(SOME_URL, formData, {
  headers: {
    'Content-Type': 'multipart/form-data',
  },
});
```

**On Success:**
```ts
const something = data.headers.contentLocation;  // Fails due to incorrect case conversion
```

If you need any more details or if there's anything else I can do to assist in the resolution process, please let me know.

Thank you for your time and attention to this matter.

**Comment by mpyw** [comment]
Thank you for your bug report. I apologize, but I've been detached from front-end development for a long time and Axios itself seems quite legacy, with apparently less usage now. Consequently, I've lost the motivation to maintain this library.

- If you submit a pull request with the bug fix, I will consider it as long as it passes the tests.
- If you are motivated to maintain this project, I am willing to appoint you as a maintainer. Since releases are automated through GitHub Actions, you should be able to handle releases yourself with maintainer privileges.

I'm sorry, but please proceed according to one of these two approaches. Thank you.

**Comment by joaolrpm** [comment]
Thank you for your prompt response and for considering my bug report. I completely understand your situation, and I appreciate your transparency about the state of the library.

While I don't have enough in-depth knowledge of the library to confidently take on the role of a maintainer, I am more than willing to contribute by submitting a pull request to address the reported bug. I plan to work on this during the next week and will ensure that the fix passes all relevant tests.

If you have any specific guidelines or preferences for the pull request, please let me know, and I'll do my best to adhere to them.

Again, thank you for your understanding, and I look forward to collaborating on resolving this issue.
