### ISSUE TITLE
React Native bug with array response

### ISSUE THREAD

**Issue by davidnum** [mpyw/axios-case-converter#7]
In RN throws iterate exception [object ArrayIterator is not iterable] where response is array of objects like 
[{ field: 'foo', message: 'bar' }]

I think this problem around "for...of" operator for array and its polyfill. This bug isnt reproducible for usualy browser enviroment, only for RN. Can you fix it?

**Comment by mpyw** [comment]
I'm using RN 54 and it's working now.

**Comment by davidnum** [comment]
> I'm using RN 54 and it's working now.
Reproducible demo: 
1. git clone https://github.com/davidnum/axios-case-converter-rn-bug.git
2. cd axios-case-converter-rn-bug
3. npm install
4. react-native run-android

**Comment by mpyw** [comment]
@davidnum Thanks, I've never tested on Android, sorry... (only iOS)

**Comment by davidnum** [comment]
> @davidnum Thanks, I've never tested on Android, sorry... (only iOS)

Can you test it? I cant discover where from this bug comes, from RN babel setup or from your transpailed code.

**Comment by davidnum** [comment]
> @davidnum Thanks, I've never tested on Android, sorry... (only iOS)

Hi! This bug caused by older android jsc version in RN, ref: https://github.com/facebook/react-native/issues/15902. Solution:
`
if (Platform.OS === 'android') {
  /* eslint-disable-next-line */
  global.Symbol = require('core-js/es6/symbol');
  require('core-js/fn/symbol/iterator');
}
`
in entry point of app, ex. index.js.

**Comment by mpyw** [comment]
@davidnum Submit your PR to be a contributor! Welcome

**Comment by davidnum** [comment]
#9
